[project]
name = "Argent-EduBattle-Backend"
version = "1.0.0"
description = "backend of Argent EduBattle​"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "dotenv>=0.9.9",
    "openai>=3.15.0",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "pytest>=7.0.0",          
    "pytest-asyncio>=0.21.0", 
    "ruff>=0.1.0",       
]

[tool.ruff]
line-length = 130
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "B", "I", "UP"]
fixable = ["ALL"]
allowed-confusables = []

[tool.ruff.lint.bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "Depends"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
