"""empty message

Revision ID: 9d3efbe8253d
Revises: 
Create Date: 2026-09-17 09:40:51.989770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d3efbe8253d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('max_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='user_role_enum'), server_default='STUDENT', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_max_id'), 'users', ['max_id'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PREPARATION', 'ACTIVE', 'FINISHED', name='room_status'), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.max_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_table('room_participants',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='student_status'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.max_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_participants')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_max_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
