"""feat: ai content column for room model

Revision ID: dc280c62767d
Revises: f9679943e272
Create Date: 2026-09-19 12:25:51.620554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc280c62767d'
down_revision: Union[str, Sequence[str], None] = 'f9679943e272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_matches', 'player2_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('room_matches', 'winner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('rooms', sa.Column('lecture', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('qualification_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('quiz_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('rooms', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'quiz_questions')
    op.drop_column('rooms', 'qualification_questions')
    op.drop_column('rooms', 'lecture')
    op.alter_column('room_matches', 'winner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('room_matches', 'player2_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
