"""delete winner column from RoomMatch

Revision ID: e3180da4b210
Revises: dc280c62767d
Create Date: 2026-09-21 13:08:21.704019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3180da4b210'
down_revision: Union[str, Sequence[str], None] = 'dc280c62767d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_matches_winner_id_fkey'), 'room_matches', type_='foreignkey')
    op.drop_column('room_matches', 'winner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_matches', sa.Column('winner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('room_matches_winner_id_fkey'), 'room_matches', 'users', ['winner_id'], ['max_id'])
    # ### end Alembic commands ###
