"""feat: Room match table

Revision ID: f9679943e272
Revises: 9d3efbe8253d
Create Date: 2026-09-17 10:36:49.000826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9679943e272'
down_revision: Union[str, Sequence[str], None] = '9d3efbe8253d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('player1_id', sa.BigInteger(), nullable=False),
    sa.Column('player2_id', sa.BigInteger(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=False),
    sa.Column('player2_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.max_id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.max_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.max_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_matches')
    # ### end Alembic commands ###
